/* No external libraries or remote resources; exported replay works offline. */
'use strict';
const $=id=>document.getElementById(id);
let pair=null, liveId=null, livePaused=false, activeRun=null;
const fmt=(x,d=1)=>x===null||x===undefined?'N/A':Number(x).toLocaleString(undefined,{maximumFractionDigits:d});
async function api(path,body){const response=await fetch('/api/'+path,body===undefined?{}:{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const data=await response.json();if(!response.ok)throw Error(typeof data.detail==='string'?data.detail:JSON.stringify(data.detail));return data;}
function settings(){return {scenario:$('scenario').value,seed:Number($('seed').value),assets:{battery_kwh:Number($('battery').value),initial_soc:$('scenario').value==='resource_exhaustion'?.2:.65},participation:Number($('participation').value)/100};}
let busy=false;async function action(fn){if(busy)return;busy=true;const buttons=[...document.querySelectorAll('.toolbar button')];buttons.forEach(b=>b.disabled=true);try{await fn();}catch(e){$('status').textContent='Could not complete action: '+e.message;}finally{busy=false;buttons.forEach(b=>b.disabled=false);}}
function card(label,value,note=''){const el=document.createElement('div');el.className='card';const l=document.createElement('div');l.className='label';l.textContent=label;const v=document.createElement('strong');v.textContent=value;const n=document.createElement('small');n.textContent=note;el.append(l,v,n);return el;}
function chart(id,series){const canvas=$(id);if(!canvas.offsetWidth)return;const width=canvas.offsetWidth,height=Number(canvas.dataset.logicalHeight||canvas.getAttribute('height')),ratio=window.devicePixelRatio||1;canvas.dataset.logicalHeight=String(height);canvas.width=width*ratio;canvas.height=height*ratio;canvas.style.height=height+'px';const c=canvas.getContext('2d');c.scale(ratio,ratio);c.clearRect(0,0,width,height);const max=Math.max(1,...series.flatMap(s=>s.values.filter(v=>v!==null)))*1.12;const left=42,right=15,top=12,bottom=28;c.font='10px system-ui';for(let j=0;j<5;j++){const y=top+(height-top-bottom)*j/4;c.strokeStyle='#e4e9e2';c.beginPath();c.moveTo(left,y);c.lineTo(width-right,y);c.stroke();c.fillStyle='#6b7c70';c.fillText(fmt(max*(1-j/4),0),2,y+3);}const n=Math.max(...series.map(s=>s.values.length));for(let j=0;j<=4;j++){const x=left+(width-left-right)*j/4;c.fillText(String(Math.round((n-1)/12*j/4)).padStart(2,'0')+':00',x-12,height-6);}for(const s of series){c.beginPath();c.strokeStyle=s.color;c.lineWidth=2;c.setLineDash(s.dash?[5,4]:[]);let started=false;s.values.forEach((v,i)=>{if(v===null)return;const x=left+(width-left-right)*i/Math.max(1,n-1),y=top+(height-top-bottom)*(1-v/max);if(started)c.lineTo(x,y);else c.moveTo(x,y);started=true;});c.stroke();}c.setLineDash([]);}
function redraw(){if(!activeRun)return;const rows=activeRun.series;chart('community-chart',[{color:'#68766a',values:rows.map(r=>r.critical_requested_kw+r.normal_requested_kw)},{color:'#127454',values:rows.map(r=>r.served_kw)},{color:'#b37827',values:rows.map(r=>r.energy_kwh)},{color:'#3b75b1',dash:true,values:rows.map((r,i)=>i?rows[i-1].forecast_next_demand_kw:null)}]);if(pair)chart('compare-chart',[{color:'#68766a',values:pair.baseline.series.map(r=>r.critical_unserved_kw+r.normal_unserved_kw)},{color:'#127454',values:pair.proposed.series.map(r=>r.critical_unserved_kw+r.normal_unserved_kw)}]);}
function render(run,source){activeRun=run;const m=run.metrics;$('source').textContent=source;$('cards').replaceChildren(card('Critical energy served',fmt(m.critical_energy_served_pct)+'%','Energy fraction · not interval availability'),card('Unserved energy',fmt(m.total_ens_kwh)+' kWh','Includes unfinished flexible obligations'),card('Peak feeder import',fmt(m.peak_import_kw)+' kW','Interval-average peak'),card('Battery at end',fmt(m.terminal_battery_kwh)+' kWh','Initial: '+fmt(m.initial_battery_kwh)+' kWh'));
$('tasks').replaceChildren(...run.tasks.map(t=>{const el=document.createElement('div');el.className='task';const name=document.createElement('span');name.textContent=t.id+(t.consent?' · opted in':' · fixed opt-out');const value=document.createElement('span');value.textContent=fmt(t.required_kwh-t.remaining_kwh)+' / '+fmt(t.required_kwh)+' kWh';el.append(name,value);return el;}));$('scrub').max=Math.max(0,run.series.length-1);$('scrub').value=Math.min(Number($('scrub').value),run.series.length-1);$('manifest').textContent=JSON.stringify(run.manifest,null,2);$('events').replaceChildren(...run.events.slice(-60).map(e=>{const el=document.createElement('div');el.className='event';el.textContent='Round '+e.round+' · '+e.event;return el;}));inspect();redraw();}
function inspect(){if(!activeRun||!activeRun.series.length){$('interval').textContent='No intervals executed yet.';$('operator-cards').replaceChildren();return;}const row=activeRun.series[Number($('scrub').value)];$('interval').textContent=row.timestamp.slice(11,16)+' · SOC '+fmt((row.soc||0)*100)+'% · '+row.action_reason+'. '+row.actuation.reason+'. Requested battery '+fmt(row.actuation.requested_kw)+' kW; actual '+fmt(row.actuation.actual_kw)+' kW.';$('operator-cards').replaceChildren(card('Forecast supply gap',fmt(row.expected_shortfall_kwh)+' kWh','Next 3 hours · conservative PV estimate'),card('Remaining task power',fmt(row.available_flexibility_kw)+' kW','Consented, active task power limits'),card('Observed connection limit',fmt(row.grid_limit_kw)+' kW','Current interval'),card('Accepted import',fmt(row.grid_import_kw)+' kW','Physical ledger output'));if(pair && activeRun===pair.proposed){const baseline=pair.baseline.series[row.step];$('operator-cards').append(card('Import difference vs B1',fmt(row.grid_import_kw-baseline.grid_import_kw)+' kW','P minus B1; negative means lower import'),card('Normal-service difference',fmt(row.normal_served_kw-baseline.normal_served_kw)+' kW','Report service changes alongside import changes'));}}
const measures=[['Critical interruption · hours','critical_interruption_hours'],['Scarcity-window critical availability · %','scarcity_critical_availability_pct'],['Scarcity window · hours','scarcity_window_hours'],['Critical ENS · kWh','critical_ens_kwh'],['Total ENS including task misses · kWh','total_ens_kwh'],['Critical energy served · %','critical_energy_served_pct'],['Critical interval availability · %','critical_availability_pct'],['Peak import · kW','peak_import_kw'],['Import energy · kWh','grid_import_kwh'],['Task completion · %','task_completion_pct'],['Unfinished tasks · kWh','flexible_missed_kwh'],['Renewable utilization · %','renewable_utilization_pct'],['Battery throughput · kWh','battery_throughput_kwh'],['Terminal battery · kWh','terminal_battery_kwh'],['Worst modeled normal service fraction','worst_household_normal_service_fraction'],['Max consecutive curtailment · min','max_consecutive_curtailment_minutes'],['Demand forecast MAE · kW','forecast_demand_mae_kw'],['PV forecast MAE · kW','forecast_pv_mae_kw'],['Fallback intervals','fallback_intervals']];
function renderPair(data,source){pair=data;render(pair.proposed,source);$('metrics').querySelector('tbody').replaceChildren(...measures.map(([label,key])=>{const tr=document.createElement('tr');for(const text of [label,fmt(pair.baseline.metrics[key],3),fmt(pair.proposed.metrics[key],3)]){const td=document.createElement('td');td.textContent=text;tr.append(td);}return tr;}));$('delta').textContent='Critical interruption hours avoided: '+fmt(pair.delta.critical_interruption_hours_avoided)+'. Critical availability gain: '+fmt(pair.delta.critical_availability_gain_pp)+' percentage points. P − B1 total ENS: '+fmt(pair.delta.total_ens_kwh)+' kWh. Critical ENS difference: '+fmt(pair.delta.critical_ens_kwh)+' kWh. ENS reduction: '+(pair.delta.ens_reduction_pct===null?'N/A (zero baseline ENS)':fmt(pair.delta.ens_reduction_pct)+'%')+'. Ending stored-energy difference: '+fmt(pair.delta.terminal_battery_difference_kwh)+' kWh. '+pair.comparison_note;}
document.querySelectorAll('[data-tab]').forEach(button=>button.onclick=()=>{document.querySelectorAll('.view').forEach(v=>v.hidden=v.id!==button.dataset.tab);document.querySelectorAll('[data-tab]').forEach(b=>b.classList.toggle('active',b===button));redraw();});
$('compare').onclick=()=>action(async()=>{$('compare').disabled=true;$('status').textContent='Computing both controllers on identical inputs…';try{renderPair(await api('comparisons',settings()),'Computed · synthetic');$('status').textContent='Comparison complete. Full-precision results are available in the export.';}finally{$('compare').disabled=false;}});
$('replay').onclick=()=>{if(!window.GRID_REPLAY){$('status').textContent='Generate the replay with the evaluation command first.';return;}renderPair(window.GRID_REPLAY,'Saved replay · synthetic');$('status').textContent='Saved cloudy-evening run, seed 7. This replay does not use the settings above.';};
$('scrub').oninput=inspect;window.addEventListener('resize',redraw);
$('export').onclick=()=>{if(!pair)return;const link=document.createElement('a');link.href=URL.createObjectURL(new Blob([JSON.stringify(pair,null,2)],{type:'application/json'}));link.download='gridsathi-comparison.json';link.click();setTimeout(()=>URL.revokeObjectURL(link.href),1000);};
$('cost-form').onsubmit=e=>{e.preventDefault();action(async()=>{const form=new FormData(e.target),costs={};for(const [k,v] of form)costs[k]=k.startsWith('existing_')?true:Number(v);const data=await api('economics',{assets:{battery_kwh:Number($('battery').value)},costs});$('cost-cards').replaceChildren(...['low','base','high'].map(k=>card(k.toUpperCase()+' · assumed','₹'+fmt(data[k].household_monthly_inr,0)+'/mo','Annual system cost ₹'+fmt(data[k].annualized_system_cost_inr,0))));$('cost-details').textContent=JSON.stringify(data,null,2);});};
$('start-run').onclick=()=>action(async()=>{if(liveId)await fetch('/api/runs/'+liveId,{method:'DELETE'});const data=await api('runs',settings());liveId=data.id;livePaused=false;await control('step',1);});
async function control(action,steps=12,fault){if(!liveId)throw Error('Start an interactive run first');const body={action,steps};if(fault)body.fault=fault;const data=await api('runs/'+liveId+'/control',body);livePaused=data.status==='paused';render(data,'Interactive · synthetic');$('live-status').textContent=data.status+' · '+data.series.length+' / '+data.scenario.critical_kw.length+' intervals. '+data.metrics.rejected_commands+' rejected commands; '+data.metrics.fallback_intervals+' fallback intervals.';}
$('step').onclick=()=>action(()=>control('step'));$('pause').onclick=()=>action(()=>control(livePaused?'resume':'pause'));$('fault').onclick=()=>action(()=>control('fault',1,'controller_failure'));$('partition').onclick=()=>action(()=>control('fault',1,'partition'));$('finish').onclick=()=>action(()=>control('complete'));$('reset').onclick=()=>action(()=>control('reset'));
api('scenarios').then(rows=>{$('scenario').replaceChildren(...rows.map(r=>{const o=document.createElement('option');o.value=r.id;o.textContent=r.name;return o;}));$('scenario').value='cloudy_evening';}).catch(()=>{$('status').textContent='Offline mode. Use the saved replay; live calculation requires the local server.';});
if(window.GRID_REPLAY)renderPair(window.GRID_REPLAY,'Saved replay · synthetic');
